version: '3.2'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - .:/app
  jruby:
    build:
      context: .
      dockerfile: Dockerfile.jruby
    volumes:
      - .:/app
