source "http://rubygems.org"

platforms :ruby do
	gem 'rjb', '> 1.3.2'
end

group :development do
  gem "rspec", "2.9.0"
  gem "bundler", "> 1.0.0"
  gem "jeweler", "> 1.5.2"
  
  platforms :jruby do
  	gem 'jruby-openssl'
  end
end
